/**
 * Permissions requises par zone de l’app — source unique pour routes (ProtectedRoute) et menu.
 */
import { PERMISSIONS } from './permissions'

export const COLIS_READ_ANY = [
  PERMISSIONS.COLIS_GROUPAGE.READ,
  PERMISSIONS.COLIS_AUTRES_ENVOIS.READ,
] as const

export const ROUTE_ACCESS = {
  dashboard: PERMISSIONS.DASHBOARD.VIEW,
  colisGroupage: PERMISSIONS.COLIS_GROUPAGE.READ,
  colisAutresEnvois: PERMISSIONS.COLIS_AUTRES_ENVOIS.READ,
  colisMap: COLIS_READ_ANY,
  colisRapports: PERMISSIONS.RAPPORTS.VIEW,
  expeditions: COLIS_READ_ANY,
  clients: PERMISSIONS.CLIENTS.READ,
  factures: PERMISSIONS.FACTURES.READ,
  paiements: PERMISSIONS.PAIEMENTS.READ,
  caisse: PERMISSIONS.CAISSE.VIEW,
  statistiques: PERMISSIONS.RAPPORTS.VIEW,
  /** Paramètres > Général (société) */
  settings: PERMISSIONS.CONFIG.VIEW,
  /** Grilles tarifaires : nécessite droit de mise à jour config */
  settingsTarifs: PERMISSIONS.CONFIG.UPDATE,
  /** Catalogue produits (CRUD tarifs catalogue) — même périmètre que création facture / colis */
  settingsCatalogueProduits: PERMISSIONS.FACTURES.CREATE,
  /** Stats d’usage des libellés marchandises (API historique catalogue) */
  settingsProduitsHistorique: PERMISSIONS.FACTURES.READ,
  /** Gestion des agences (CRUD UI) */
  settingsAgences: PERMISSIONS.CONFIG.UPDATE,
  /** Liste agences (API) — souvent couvert par structures.agences.read → agences.read */
  agencesList: PERMISSIONS.AGENCES.READ,
  users: PERMISSIONS.USERS.READ,
  litiges: PERMISSIONS.LITIGES.VIEW,
  callcenterInbox: PERMISSIONS.CALLCENTER.INBOX,
  exploitationDashboard: [
    PERMISSIONS.EXPLOITATION.CREDITS_READ,
    PERMISSIONS.EXPLOITATION.CREDITS_MANAGE,
    PERMISSIONS.EXPLOITATION.CREDITS_SUBMIT_RECAP,
    PERMISSIONS.EXPLOITATION.POINTS_READ,
    PERMISSIONS.EXPLOITATION.POINTS_CREATE,
    PERMISSIONS.EXPLOITATION.POINTS_SUBMIT,
    PERMISSIONS.EXPLOITATION.POINTS_VALIDATE,
  ],
  exploitationCredits: [
    PERMISSIONS.EXPLOITATION.CREDITS_READ,
    PERMISSIONS.EXPLOITATION.CREDITS_MANAGE,
    PERMISSIONS.EXPLOITATION.CREDITS_SUBMIT_RECAP,
  ],
  exploitationPointsJournaliers: [
    PERMISSIONS.EXPLOITATION.POINTS_READ,
    PERMISSIONS.EXPLOITATION.POINTS_CREATE,
    PERMISSIONS.EXPLOITATION.POINTS_SUBMIT,
    PERMISSIONS.EXPLOITATION.POINTS_VALIDATE,
  ],
  agenceCreditsRecap: PERMISSIONS.EXPLOITATION.CREDITS_SUBMIT_RECAP,
  agencePointJournalier: [
    PERMISSIONS.EXPLOITATION.POINTS_CREATE,
    PERMISSIONS.EXPLOITATION.POINTS_SUBMIT,
  ],
  exploitationFournitures: [
    PERMISSIONS.EXPLOITATION.FOURNITURES_READ,
    PERMISSIONS.EXPLOITATION.FOURNITURES_MANAGE,
    PERMISSIONS.EXPLOITATION.FOURNITURES_REQUEST,
  ],
  agenceFournituresDemande: [
    PERMISSIONS.EXPLOITATION.FOURNITURES_REQUEST,
    PERMISSIONS.EXPLOITATION.FOURNITURES_MANAGE,
  ],
} as const
