import { DataSource } from 'typeorm';
import {
  ProduitCatalogue,
  CategoriesProduit,
  NaturePrix,
} from '../../produits-catalogue/entities/produit-catalogue.entity';

export async function seedProduitsCatalogue(dataSource: DataSource) {
  const produitRepository = dataSource.getRepository(ProduitCatalogue);

  const normalizeKey = (raw: string): string =>
    String(raw || '')
      .trim()
      .toUpperCase()
      .normalize('NFD')
      .replace(/\p{Diacritic}/gu, '')
      .replace(/\s+/g, ' ');

  // Index en mémoire pour éviter N requêtes et gérer accents/espaces
  const existingAll = await produitRepository.find();
  const existingByKey = new Map<string, ProduitCatalogue>();
  for (const p of existingAll) {
    existingByKey.set(normalizeKey(p.nom), p);
  }

  const upsert = async (row: Partial<ProduitCatalogue>) => {
    const nom = String(row.nom || '').trim();
    if (!nom) return;
    const key = normalizeKey(nom);
    const found = existingByKey.get(key) ?? null;

    if (!found) {
      const created = (await produitRepository.save(
        produitRepository.create({
          ...row,
          nom,
          actif: row.actif ?? true,
        } as any),
      )) as unknown as ProduitCatalogue;
      existingByKey.set(key, created);
      return;
    }
    await produitRepository.update(
      { id: found.id } as any,
      {
        ...row,
        nom: found.nom, // ne pas renommer automatiquement en prod
        actif: row.actif ?? found.actif,
      } as any,
    );
  };

  // ─────────────────────────────────────────────────────────────────────────
  // GROUPAGE CARGO SP-CI — ABIDJAN → PARIS
  // ─────────────────────────────────────────────────────────────────────────

  const produits = [
    // ========== CATÉGORIE: DENRÉE — 900 FCFA/kg, forfait 0–4 kg : 3 500 F ==========
    {
      nom: 'DENREES ALIMENTAIRES',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'ATTIEKE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'PLACALI',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GARI',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'CHAT NOIR',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE CACAO',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GOMBO',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GNANGNAN',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'FEUILLE DE PATATE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'SOUMARA',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: "PATE D'ARACHIDE",
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'DORKOUNOU',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'AKASSA',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'CHIPS',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    // Alias orthographe
    {
      nom: 'SHIPS',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'BISSAP',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'TAMARIN',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'PATE DE GINGEMBRE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE MIL',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE MAIS',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE PIMENT',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE GINGEMBRE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GINGEMBRE SECHE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'POUDRE DE GOMBO',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'MIL',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'HARICOT',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'TCHONGON',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'RIZ',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'ANANAS SECHE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'MANGUE SECHE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'COUSCOUS',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'AROME',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GRAINE PILE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'EPICE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'MAIS',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'GNONMI',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'BAOBAB',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'BONBON',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'CACAHOUETTE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'CROQUETTE',
      categorie: CategoriesProduit.DENREE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 900,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },

    // ========== CATÉGORIE: HUILE ET KARITÉ — 1 100 FCFA/kg, forfait 0–4 kg : 4 500 F ==========
    {
      nom: 'PETIT COLAS',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'HUILE DE COCO',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'BEURRE DE KARITE',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'KINKELIBA',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'DJEKA',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },
    {
      nom: 'INFUSION',
      categorie: CategoriesProduit.HUILE_ET_KARITE,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1100,
      prix_forfaitaire: 4500,
      poids_min: 0,
      poids_max: 4,
      description: 'A PARTIR DE 5 KG',
      unite: 'kg',
    },

    // ========== CATÉGORIE: DIVERS — 1 850 FCFA/kg, forfait 0–2 kg : 5 000 F ==========
    {
      nom: 'VETEMENTS',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CHAUSSURES',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'DRAPS',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'OUVRAGE EN PLASTIQUE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'USTENSILES DE CUISINE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'VALISE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'ENCENS',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'SAVOIR NOIR',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'SAC A MAIN',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: "L'EAU BENITE",
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'ECORCE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: '4 COTES',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CAOLIN',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'NEP NEP',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1850,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // DIVERS spéciaux — Attoté : 2 100 FCFA/kg, forfait 0–2 kg : 5 000 F
    {
      nom: 'ATTOTE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 2100,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // DIVERS spéciaux — Huile rouge : 1 600 FCFA/kg, forfait 0–2 kg : 3 500 F
    {
      nom: 'HUILE ROUGE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1600,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'BOUILLONS',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1600,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CUBE MAGGI',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 1600,
      prix_forfaitaire: 3500,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // DIVERS de marque — 3 500 FCFA/kg, forfait 0–2 kg : 5 000 F
    {
      nom: 'VETEMENTS DE MARQUE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 3500,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CHAUSSURES DE MARQUE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 3500,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'SACS DE MARQUE',
      categorie: CategoriesProduit.DIVERS,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 3500,
      prix_forfaitaire: 5000,
      poids_min: 0,
      poids_max: 2,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // ─────────────────────────────────────────────────────────────────────────
    // COLIS RAPIDE CA-CI — ABIDJAN → PARIS
    // ─────────────────────────────────────────────────────────────────────────

    // ========== CATÉGORIE: COLIS_RAPIDE_EXPORT — 5 500 FCFA/kg, forfait 0–1 kg : 7 500 F ==========
    {
      nom: 'POISSON FUME',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CREVETTE FUMEE',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'ESCARGOT',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'POULET FUME',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'POISSON EN POUDRE',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'CREVETTE EN POUDRE',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'KPLO FUME',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },
    {
      nom: 'VIANDE FUME',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5500,
      prix_forfaitaire: 7500,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // Cosmétique — 5 850 FCFA/kg, forfait 0–1 kg : 8 000 F
    {
      nom: 'COSMETIQUE',
      categorie: CategoriesProduit.COLIS_RAPIDE_EXPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 5850,
      prix_forfaitaire: 8000,
      poids_min: 0,
      poids_max: 1,
      description: 'A PARTIR DE 2 KG',
      unite: 'kg',
    },

    // ─────────────────────────────────────────────────────────────────────────
    // COLIS RAPIDE CA-FR — PARIS → ABIDJAN
    // Tarif facturé en euros (taux fixe : 1 € = 655,957 FCFA)
    // ─────────────────────────────────────────────────────────────────────────

    // ========== CATÉGORIE: COLIS_RAPIDE_IMPORT — 11 €/kg = 7 216 FCFA ==========
    {
      nom: 'DENREES ET DIVERS IMPORT',
      categorie: CategoriesProduit.COLIS_RAPIDE_IMPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 7216,
      description: '11 €/kg — Paris → Abidjan',
      unite: 'kg',
    },

    // Téléphone et électronique — À partir de 18 €/kg = 11 807 FCFA
    {
      nom: 'TELEPHONE ET APPAREIL ELECTRONIQUE',
      categorie: CategoriesProduit.COLIS_RAPIDE_IMPORT,
      nature: NaturePrix.PRIX_UNITAIRE,
      prix_unitaire: 11807,
      description: 'À partir de 18 €/kg — Paris → Abidjan',
      unite: 'kg',
    },
  ];

  // Upsert : ajoute les manquants + met à jour prix/forfaits si besoin
  for (const p of produits) {
    // Correction de saisie fréquente : "POUDRE DE MAÏS" -> "POUDRE DE MAIS"
    if (p.nom === 'POUDRE DE MAÏS') (p as any).nom = 'POUDRE DE MAIS';
    await upsert(p as any);
  }
  console.log(`✅ Catalogue produits enrichi : ${produits.length} lignes traitées`);
}
